repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff-format
        entry: uvx -- ruff format
        language: system
        types: [python]

      - id: ruff-check
        name: ruff-check
        entry: uvx -- ruff check --fix
        language: system
        types: [python]

      - id: ty-check
        name: ty-check
        entry: uvx -- ty check
        language: system
        types: [python]

      - id: zensical-build
        name: zensical-build
        entry: uv run zensical build --strict
        language: system
        pass_filenames: false
        types: [markdown]

      - id: zizmor
        name: zizmor
        entry: uvx -- zizmor
        language: system
        types: [yaml]
