[project]
site_name = "Eksperiment"
nav = [
  {"Home" = "index.md"},
  {"Tutorials" = [
    "tutorials/experiment.md",
  ]},
  {"API Reference" = [
    "api/eksperiment/experiment.md",
    "api/eksperiment/logging/interfaces.md",
    "api/eksperiment/logging/adapters.md",
  ]},
]

[project.plugins.mkdocstrings]

[project.plugins.mkdocstrings.handlers.python]
paths = ["src"]

[project.plugins.mkdocstrings.handlers.python.options]
docstring_style = "google"
show_docstring_description = true
show_docstring_parameters = true
